---
- name: Create docker volumes directories
  file: path="{{ item }}" state=directory
  with_items:
    - "{{ bind_oonibackend_data_path }}"
    - "{{ bind_archive_dir }}"
    - "{{ bind_tor_datadir }}"
    - "{{ bind_deck_dir }}"
    - "{{ bind_input_dir }}"
    - "{{ bind_report_dir }}"
    - "{{ bind_oonibackend_log_path }}"
    - "{{ bind_oonibackend_conf_path }}"

- name: Generate Dockerfile template
  template: >
    backup=yes
    src="Dockerfile.j2"
    dest="{{ docker_file }}"
    unsafe_writes=true

- name: Build docker image
  docker_image: >
    state=present
    timeout=1500
    name="{{ docker_img_name }}"
    path="{{ bind_oonibackend_data_path }}"
    nocache=True

- name: Generate oonibackend.conf template
  template: >
    backup=yes
    src="oonibackend.conf.j2"
    dest="{{ bind_oonibackend_conf }}"
    unsafe_writes=true
