---
- include: tls.yml
  when: letsencrypt_set is defined and set_letsencrypt == 'true'
- include: install.yml
- include: configure.yml
- include: supervisord.yml
  when: set_supervisord is defined and set_supervisord == 'true'
- include: populate_bouncer_base.yml
  when: set_populate_bouncer_base
