---
- name: Wait for hidden services to bootstrap
  wait_for: >
    path="{{ oonibackend_log_path }}/{{ oonibackend_log_file_name }}"
    search_regex="Started hidden service"
    delay="30"

- name: Assign hidden services hostnames to variables
  shell: cat "{{ item }}/hostname"
  register: "{{ item }}_hostname"
  failed_when: "{{ item }}_hostname.rc not in [0, 1]"
  when: enable_bouncer == "yes"
  with_items:
    - bouncer_hsdir
    - collector_hsdir

- name: Assign hidden services hostnames to variables
  shell: cat "{{ item }}/hostname"
  register: "{{ item }}_hostname"
  failed_when: "{{ item }}_hostname.rc not in [0, 1]"
  when: enable_web_connectivity == "yes"
  with_items:
    - web_connectivity_hsdir
    - collector_hsdir

- name: Template "{{ bouncer_file }}"
  template: >
    src="bouncer_base.yaml.j2"
    dest="{{ bouncer_file }}"
    backup="yes"
    when: enable_bouncer == "yes"
